<?php

/**
 * @file
 * Install hooks for oclsdora.
 */

/**
 * Implements hook_install().
 */
function oclsdora_install() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('oclsdora');
}

/**
 * Implements hook_uninstall().
 */
function oclsdora_uninstall() {
  module_load_include('inc', 'islandora', 'includes/solution_packs');
  islandora_install_solution_pack('oclsdora', 'uninstall');
}
