<?php

/**
 * @file
 * Customizations for the Ontario Colleges Library Service.
 */

/**
 * Implements hook_islandora_xml_form_builder_form_associations().
 */
function oclsdora_islandora_xml_form_builder_form_associations() {
  $associations = array(
    'bceln_artwork_form' => array(
      'content_model' => 'islandora:sp_large_image_cmodel',
      'form_name' => 'BC ELN Artwork Form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'self_transform' => 'islandora_cleanup_mods_extended.xsl',
      'template' => FALSE,
    ),
    'bceln_audio_form' => array(
      'content_model' => 'islandora:sp-audioCModel',
      'form_name' => 'BC ELN Audio Form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'self_transform' => 'islandora_cleanup_mods_extended.xsl',
      'template' => FALSE,
    ),
    'bceln_basic_image_form' => array(
      'content_model' => 'islandora:sp_basic_image',
      'form_name' => 'BC ELN Basic Image Form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'self_transform' => 'islandora_cleanup_mods_extended.xsl',
      'template' => FALSE,
    ),
    'bceln_citation_form' => array(
      'content_model' => 'ir:citationCModel',
      'form_name' => 'BC ELN Citation Form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'self_transform' => 'islandora_cleanup_mods_extended.xsl',
      'template' => FALSE,
    ),
    'bceln_newspaper_issue_form' => array(
      'content_model' => 'islandora:newspaperIssueCModel',
      'form_name' => 'BC ELN Newspaper Issue Form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'self_transform' => 'islandora_cleanup_mods_extended.xsl',
      'template' => FALSE,
    ),
    'bceln_thesis_form' => array(
      'content_model' => 'ir:thesisCModel',
      'form_name' => 'BC ELN Thesis Form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'self_transform' => 'islandora_cleanup_mods_extended.xsl',
      'template' => FALSE,
    ),
    'bceln_video_form' => array(
      'content_model' => 'islandora:sp_videoCModel',
      'form_name' => 'BC ELN Video Form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'self_transform' => 'islandora_cleanup_mods_extended.xsl',
      'template' => FALSE,
    ),
    'bceln_serials_form_root_serial' => array(
      'content_model' => 'islandora:rootSerialCModel',
      'form_name' => 'BC ELN Serials Form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfoTab', 'titleInfoPanel', 'titleInfo'),
      'transform' => 'mods_to_dc.xsl',
      'self_transform' => 'islandora_cleanup_mods_extended.xsl',
      'template' => FALSE,
    ),
    'bceln_serials_form_stub' => array(
      'content_model' => 'islandora:intermediateSerialCModelStub',
      'form_name' => 'BC ELN Serials Form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfoTab', 'titleInfoPanel', 'titleInfo'),
      'transform' => 'mods_to_dc.xsl',
      'self_transform' => 'islandora_cleanup_mods_extended.xsl',
      'template' => FALSE,
    ),
    'bceln_serials_form_intermediate' => array(
      'content_model' => 'islandora:intermediateCModel',
      'form_name' => 'BC ELN Serials Form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfoTab', 'titleInfoPanel', 'titleInfo'),
      'transform' => 'mods_to_dc.xsl',
      'self_transform' => 'islandora_cleanup_mods_extended.xsl',
      'template' => FALSE,
    ),
  );
  $base_models = array(
    'audio' => 'islandora:sp-audioCModel',
    'video' => 'islandora:sp_videoCModel',
    'pdf' => 'islandora:sp_pdf',
    'binary' => 'islandora:binaryObjectCModel',
    'collection' => 'islandora:collectionCModel',
    'large_image' => 'islandora:sp_large_image_cmodel',
    'book' => 'islandora:bookCModel',
    'basic_image' => 'islandora:sp_basic_image',
    'document' => 'islandora:sp_document_collection',
  );
  $mods_base = array(
    'form_name' => 'OCLS Base MODS Form',
    'dsid' => 'MODS',
    'title_field' => array('titles', '0', 'title'),
    'transform' => 'mods_to_dc.xsl',
    'template' => FALSE,
    'self_transform' => 'islandora_cleanup_mods_extended.xsl',
  );
  foreach ($base_models as $key => $model) {
    $associations["base_mods_$key"] = array(
      'content_model' => $model,
    ) + $mods_base;
  }
  return $associations;
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function oclsdora_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'oclsdora');
  return array(
    'BC ELN Artwork Form' => array(
      'form_file' => "$module_path/xml/bceln_artwork_form.xml",
    ),
    'BC ELN Audio Form' => array(
      'form_file' => "$module_path/xml/bceln_audio_form.xml",
    ),
    'BC ELN Basic Image Form' => array(
      'form_file' => "$module_path/xml/bceln_basc_image_form.xml",
    ),
    'BC ELN Citation Form' => array(
      'form_file' => "$module_path/xml/bceln_citation_form.xml",
    ),
    'BC ELN Newspaper Issue Form' => array(
      'form_file' => "$module_path/xml/bceln_newspaper_issue_form.xml",
    ),
    'BC ELN Thesis Form' => array(
      'form_file' => "$module_path/xml/bceln_thesis_form.xml",
    ),
    'BC ELN Video Form' => array(
      'form_file' => "$module_path/xml/bceln_video_form.xml",
    ),
    'BC ELN Serials Form' => array(
      'form_file' => "$module_path/xml/bceln_serials_form.xml",
    ),
    'OCLS Base MODS Form' => array(
      'form_file' => "$module_path/xml/ocls_base_mods_form.xml",
    ),
  );
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds autocomplete for the custom bceln citation and thesis forms.
 */
function oclsdora_form_xml_form_builder_datastream_form_alter(&$form, &$form_state, $form_id) {
  if (module_exists('islandora_scholar') && module_exists('islandora_entities')) {
    module_load_include('inc', 'islandora_entities', 'includes/utilities');
    if (isset($form_state['association']['id'])) {
      $id = $form_state['association']['id'];
      if (strcmp($id, 'bceln_citation_form') == 0) {
        islandora_entities_add_autocompletes_to_citation_form($form);
      }
      elseif (strcmp($id, 'bceln_thesis_form') == 0) {
        islandora_entities_add_autocompletes_to_thesis_form($form);
      }
    }
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 *
 * Adds autocomplete for the custom bceln citation and thesis forms.
 */
function oclsdora_form_xml_form_builder_ingest_form_alter(&$form, &$form_state, $form_id) {
  if (module_exists('islandora_scholar') && module_exists('islandora_entities')) {
    module_load_include('inc', 'islandora_entities', 'includes/utilities');
    if (isset($form_state['islandora']['step_storage']['xml_form_builder_metadata_step']['association']['id'])) {
      $id = $form_state['islandora']['step_storage']['xml_form_builder_metadata_step']['association']['id'];
      if (strcmp($id, 'bceln_citation_form') == 0) {
        islandora_entities_add_autocompletes_to_citation_form($form);
      }
      elseif (strcmp($id, 'bceln_thesis_form') == 0) {
        islandora_entities_add_autocompletes_to_thesis_form($form);
      }
    }
  }
}

/**
 * Implements hook_islandora_required_objects().
 */
function oclsdora_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'oclsdora');

  $namespaces = array(
    'seneca',
    'conestoga',
    'fleming',
    'centennial',
    'loyalist',
    'georgian',
  );

  // Create objects.
  $collections = array();
  foreach ($namespaces as $ns) {
    $collections[$ns] = $connection->repository->constructObject("$ns:root");
  }

  // Populate base objects.
  foreach ($collections as $object) {
    $object->owner = 'fedoraAdmin';
    $object->models = 'islandora:collectionCModel';
    $object->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  }

  // Populate Labels.
  $labels = array(
    'seneca' => 'Seneca',
    'conestoga' => 'Conestoga',
    'fleming' => 'Fleming',
    'centennial' => 'Centennial',
    'loyalist' => 'Loyalist',
    'georgian' => 'Georgian',
  );
  foreach ($labels as $ns => $label) {
    $collections[$ns]->label = $label;
  }

  // Populate TNs.
  $tns = array(
    'seneca' => "$module_path/images/seneca-libraries-logo.png",
    'conestoga' => "$module_path/images/conestoga-logo.jpg",
    'fleming' => "$module_path/images/fleming_png.png",
    'centennial' => "$module_path/images/centennial_jpg.jpg",
    'loyalist' => "$module_path/images/loyalist_library.jpg",
    'georgian' => "$module_path/images/georgian_png.png",
  );
  $mimes = array(
    'seneca' => 'image/png',
    'conestoga' => 'image/jpeg',
    'fleming' => 'image/png',
    'centennial' => 'image/jpeg',
    'loyalist' => 'image/jpeg',
    'georgian' => 'image/png',
  );
  foreach ($tns as $ns => $path) {
    $datastream = $collections[$ns]->constructDatastream('TN', 'M');
    $datastream->label = 'Thumbnail';
    $datastream->mimetype = $mimes[$ns];
    $datastream->setContentFromFile($path, FALSE);
    $collections[$ns]->ingestDatastream($datastream);
  }

  // Populate collection policies.
  $collection_policies = array(
    'seneca' => "$module_path/xml/collection_policies/seneca.xml",
    'conestoga' => "$module_path/xml/collection_policies/conestoga.xml",
    'fleming' => "$module_path/xml/collection_policies/fleming.xml",
    'centennial' => "$module_path/xml/collection_policies/centennial.xml",
    'loyalist' => "$module_path/xml/collection_policies/loyalists.xml",
    'georgian' => "$module_path/xml/collection_policies/georgian.xml",
  );
  foreach ($collection_policies as $ns => $path) {
    $datastream = $collections[$ns]->constructDatastream('COLLECTION_POLICY', 'M');
    $datastream->label = 'Collection policy';
    $datastream->mimetype = 'application/xml';
    $datastream->setContentFromFile($path, FALSE);
    $collections[$ns]->ingestDatastream($datastream);
  }

  return array(
    'oclsdora' => array(
      'title' => 'Oclsdora',
      'objects' => array_values($collections),
    ),
  );
}
